### ISSUE TITLE
Not seeing rake transactions in New Relic

### ISSUE THREAD

**Issue by Sovietaced** [xinminlabs/newrelic-rake#12]
Not sure if the directions aren't idiot proof enough but I have the gem running production but I don't see any transactions listed for my rake tasks. To make sure the agent and the gem were running I included the following within my rake tasks. 

require 'newrelic-rake'
NewRelic::Agent.manual_start

Running rails 4.0.2

**Comment by Sovietaced** [comment]
If it helps at all, when I include what i posted above exceptions are recorded in New Relic errors. If I do not include the two lines exceptions are not reported. So including the two lines helps but still does not trace transactions.

**Comment by flyerhzm** [comment]
@Sovietaced did you see `Installing Rake instrumentation` in your newrelic log?

**Comment by flyerhzm** [comment]
@Sovietaced I have verifid newrelic-rake 1.4.1 with newrelic_rpm 3.7.2.192 on production, it works perfect, I didn't add any specific code
