### ISSUE TITLE
Setup needed for plain tasks

### ISSUE THREAD

**Issue by schnittchen** [xinminlabs/newrelic-rake#8]
This gem works like a charm for rails projects and rake tasks with the :environment dependency. Other rake tasks don't appear in NR.

I analyzed this a bit and found out :environment tasks are caught because
- people usually do Bundler.require in their application.rb
- the newrelic_rpm gem has a railtie with an initializer starting the agent

These prerequisits amount roughly to this setup:

```
require 'newrelic-rake'
NewRelic::Agent.manual_start
```

Placing these lines in the rake file should make things work for all tasks.

**Comment by flyerhzm** [comment]
thanks for pointing it out, would you mind opening a pull request for this?

**Comment by schnittchen** [comment]
What do you mean? Should it be mentioned in the README?

**Comment by flyerhzm** [comment]
yes, please add it in Usage section.

**Comment by schnittchen** [comment]
Are you ok with this version? https://github.com/schnittchen/newrelic-rake/tree/issue-8

**Comment by flyerhzm** [comment]
@schnittchen looks good except one typo 'environent'
